server:
  port: 8080
  error:
    include-stacktrace: "ALWAYS"

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hiberenvers?currentSchema=public
    username: postgres
    password: postgrespass
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-active: 30
      max-idle: 18
      min-idle: 7
      initial-size: 3
      time-between-eviction-runs-millis: 34000
      min-evictable-idle-time-millis: 55000
      validation-query: "SELECT 1"
      validation-interval: 34000
      test-on-borrow: true
      remove-abandoned: true
      remove-abandoned-timeout: 55
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
